### PR TITLE
Ch13711/add tslint unused expression package to guild

### PR DESCRIPTION
**Pull request by travishaby**
What does this PR do?
--------------------
Adds `tslint-no-unused-expression-chai` to this shared config. Will fix issue https://github.com/GuildEducationInc/tslint-config-guild/issues/1

What's the related story?
---------------------------
[Clubhouse Card](https://app.clubhouse.io/guild/story/13711/add-tslint-unused-expression-package-to-guild-tslint-config)

Giphy please
-----------------

### CODE REVIEW

**Review by SerKnight — APPROVED** [review]
^__^

**Review by sdrioux — APPROVED** [review]

**Review by kayeight — APPROVED** [review]

**Comment by wingrunr21** [comment]
Just remember that every package we add here will also need to be supported in CodeClimate for the rules to be applied

**Comment by sdrioux** [comment]
He makes a good point, I'm not seeing it here: https://github.com/tkqubo/codeclimate-tslint/blob/master/package.json

**Comment by travishaby** [comment]
derp derp, forgot about that

**Comment by wingrunr21** [comment]
It probably isn’t unreasonable to add it to CodeClimate. There was a core TSLint issue about it

https://github.com/palantir/tslint/issues/2614

**Comment by travishaby** [comment]
Word, I may push a PR to their repo :D

**Comment by travishaby** [comment]
He merged it so I think this should work now? https://github.com/tkqubo/codeclimate-tslint/pull/53

**Pull request merged**
